# Generated by Django 5.1.4 on 2024-12-10 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tech stack',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in_development', 'In Development'), ('completed', 'Completed'), ('archived', 'Archived'), ('paused', 'Paused')], default='in_development', max_length=20)),
                ('repo_url', models.URLField()),
                ('deploy_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'project tag',
                'verbose_name_plural': 'project tags',
                'unique_together': {('project', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(through='portfolio.ProjectTag', to='portfolio.tag'),
        ),
        migrations.CreateModel(
            name='ProjectTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.techstack')),
            ],
            options={
                'verbose_name': 'project tech stack',
                'unique_together': {('project', 'tech_stack')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(through='portfolio.ProjectTechStack', to='portfolio.techstack'),
        ),
    ]
