# Generated by Django 5.1.4 on 2025-01-02 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('project', models.ManyToManyField(blank=True, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('audio', 'Audio)'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='media/')),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tag')),
            ],
            options={
                'verbose_name': 'post tag',
                'verbose_name_plural': 'post tags',
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(through='blog.PostTag', to='projects.tag'),
        ),
        migrations.CreateModel(
            name='PostTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.techstack')),
            ],
            options={
                'verbose_name': 'post tech stack',
                'unique_together': {('post', 'tech_stack')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tech_stack',
            field=models.ManyToManyField(through='blog.PostTechStack', to='projects.techstack'),
        ),
    ]
